name: Minimal Dispatch Event

on:
  repository_dispatch:
    types: [trigger-workflow]

jobs:
  print-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Print a test message
        run: echo "This is a test message"
